### ISSUE TITLE
Chunky using 100% CPU

### ISSUE THREAD

**Issue by LuzrodGaming** [pop4959/Chunky#152]
Hi there,

I tried generating chunks within a 10k blocks radius but Chunky crashes my server everytime because it takes 100% of the CPU.

Are you planning on adding some settings to limit CPU usage for Chunky, or a CPS limit ?

**Comment by pop4959** [comment]
First off, I would recommend checking if you are affected by [MC-245406](https://bugs.mojang.com/browse/MC-245406). This has been known widely to impact people who are trying to upgrade old worlds.

If that's not the issue, please use the [Discord](https://discord.gg/ZwVJukcNQG) server for help with further troubleshooting. Most CPU issues are not caused directly by chunky but by other issues with the server. More than happy to look through things, but generally limiting the task itself is a bad solution (and usually doesn't work well if at all since it avoids the real problems).

**Comment by LuzrodGaming** [comment]
I've checked [MC-245406](https://bugs.mojang.com/browse/MC-245406) and I confirm that I'm affected by that bug.

Thanks alot :)

**Comment by pop4959** [comment]
No problem, that one has been quite common (and annoying to many server owners) recently.

**Comment by molor** [comment]
MC-245406 was fixed in latest Paper, but anyway, @pop4959 could you add cps limiter or something like that?

I want to run chunk pregenerator task in "light mode" in background, so it's will generate new chunks but, at the same time, it will not interfere with other players to play, taking away all the performance

I'm even surprised that such a cool and popular plugin still doesn't have such an opportunity

**Comment by molor** [comment]
(yeah I found #4 but it seems to be dead?..)

**Comment by pop4959** [comment]
> MC-245406 was fixed in latest Paper, but anyway, @pop4959 could you add cps limiter or something like that?
>
> I want to run chunk pregenerator task in "light mode" in background, so it's will generate new chunks but, at the same time, it will not interfere with other players to play, taking away all the performance
> 
> I'm even surprised that such a cool and popular plugin still doesn't have such an opportunity

At the time of writing it was not fixed yet, but yes downloading the latest Paper should work now for that issue.

A cps limiter is something I'd considered but it's very low priority, if it's even needed at all kinda due to the fact that chunk generation really doesn't hurt server performance since 1.13. The worst that'll happen generally is chunk loading will be slightly slower for players if there are any online at the same time.

However, you're really not doing yourself a favor if you are trying to "pre-generate" (which literally means "generating before") with players online, as it defeats the point of doing so in the first place. This is because not only do you miss out on the performance benefit of having done it beforehand, but you're also pushing generation even harder while players are online and making the experience worse for them. Basically, just don't do it. It's a bad idea.
